import "./globals.css";
import { Inter } from "next/font/google";
import AuthProviderPro from "@/Components/AuthProviderFiles/AuthProviderPro";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Free Flow",
  description: "Generated by Team Mern Militia",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <AuthProviderPro>
          <div className="outlineSpace">{children}</div>
        </AuthProviderPro>
      </body>
    </html>
  );
}
